import React from 'react';
import { motion } from 'motion/react';
import { Shield, Lock, Scale, Eye, AlertTriangle, FileCheck, Landmark, ShieldCheck, Zap } from 'lucide-react';

const TrustSafetyCompliance = () => {
    const sections = [
        {
            id: 'privacy',
            title: "1. Our Core Promise: 'Your Data is Yours'",
            icon: <Lock className="w-5 h-5 text-primary" />,
            content: (
                <div className="space-y-4">
                    <p className="text-subtext italic">We operate under a strict "Zero-Training" policy for our paid workspaces. This is our primary differentiator from consumer-grade AI tools.</p>
                    <ul className="space-y-3">
                        <li className="flex gap-3">
                            <ShieldCheck className="w-5 h-5 text-green-500 shrink-0" />
                            <div>
                                <h4 className="font-semibold text-maintext">No Model Training</h4>
                                <p className="text-sm text-subtext">We do NOT use your private workspace data (documents, chat logs, images) to train our public AI models.</p>
                            </div>
                        </li>
                        <li className="flex gap-3">
                            <ShieldCheck className="w-5 h-5 text-green-500 shrink-0" />
                            <div>
                                <h4 className="font-semibold text-maintext">Data Isolation</h4>
                                <p className="text-sm text-subtext">Your data is processed in isolated containers within Google Cloud’s secure infrastructure.</p>
                            </div>
                        </li>
                        <li className="flex gap-3">
                            <ShieldCheck className="w-5 h-5 text-green-500 shrink-0" />
                            <div>
                                <h4 className="font-semibold text-maintext">Intellectual Property (IP) Ownershipt</h4>
                                <p className="text-sm text-subtext">You retain 100% ownership rights to all content generated by our AI agents (text, images, and video).</p>
                            </div>
                        </li>
                    </ul>
                </div>
            )
        },
        {
            id: 'compliance',
            title: "2. Compliance with Indian Law (DPDP Act 2023)",
            icon: <Landmark className="w-5 h-5 text-primary" />,
            content: (
                <div className="space-y-3">
                    <p className="text-subtext">We are fully compliant with the Digital Personal Data Protection (DPDP) Act, 2023. As a "Data Fiduciary," we adhere to the following mandatory standards:</p>
                    <ul className="list-disc list-inside text-sm text-subtext space-y-2 ml-2">
                        <li><strong>Consent Architecture:</strong> We collect only the data necessary. You have the right to withdraw consent at any time.</li>
                        <li><strong>Grievance Redressal:</strong> Data Protection Officer (DPO) based in India handles privacy complaints within 72 hours. Contact: <a href="mailto:privacy@a-series.in" className="text-primary hover:underline">privacy@a-series.in</a></li>
                        <li><strong>Right to be Forgotten:</strong> Upon request, we permanently delete all account data, history, and assets within 30 days.</li>
                    </ul>
                </div>
            )
        },
        {
            id: 'security',
            title: "3. Technical Security (The 'Vertex Shield')",
            icon: <Shield className="w-5 h-5 text-primary" />,
            content: (
                <div className="overflow-hidden border border-border rounded-xl">
                    <table className="w-full text-left text-sm">
                        <thead className="bg-secondary/50 text-maintext font-bold">
                            <tr>
                                <th className="p-3 border-b border-border">Layer</th>
                                <th className="p-3 border-b border-border">Security Measure</th>
                            </tr>
                        </thead>
                        <tbody className="text-subtext">
                            <tr>
                                <td className="p-3 border-b border-border font-medium text-maintext">Encryption</td>
                                <td className="p-3 border-b border-border">Data encrypted at rest (AES-256) and in transit (TLS 1.2+).</td>
                            </tr>
                            <tr>
                                <td className="p-3 border-b border-border font-medium text-maintext">Data Residency</td>
                                <td className="p-3 border-b border-border">Prioritized storage in Google Cloud India regions (Mumbai/Delhi).</td>
                            </tr>
                            <tr>
                                <td className="p-3 border-b border-border font-medium text-maintext">Access Control</td>
                                <td className="p-3 border-b border-border">Strict IAM policies. Engineers cannot view private chats without explicit audit.</td>
                            </tr>
                            <tr>
                                <td className="p-3 font-medium text-maintext">Certifications</td>
                                <td className="p-3">Google Cloud infrastructure is ISO 27001, SOC 2 Type II, and GDPR compliant.</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            )
        },
        {
            id: 'usage',
            title: "4. Acceptable Use Policy (Ethical Guardrails)",
            icon: <AlertTriangle className="w-5 h-5 text-primary" />,
            content: (
                <div className="space-y-4">
                    <p className="text-sm text-subtext">To maintain a safe ecosystem, we enforce strict guidelines on how our AI Agents can be used. We strictly prohibit:</p>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div className="p-3 bg-red-500/5 border border-red-500/10 rounded-lg">
                            <h4 className="font-bold text-maintext text-xs uppercase mb-2">Prohibited Content</h4>
                            <ul className="text-xs text-subtext space-y-1">
                                <li>• NSFW/Adult Content</li>
                                <li>• Hate Speech & Discrimination</li>
                                <li>• Deepfakes & Impersonation</li>
                            </ul>
                        </div>
                        <div className="p-3 bg-amber-500/5 border border-amber-500/10 rounded-lg">
                            <h4 className="font-bold text-maintext text-xs uppercase mb-2">High-Risk Use Cases</h4>
                            <ul className="text-xs text-subtext space-y-1">
                                <li>• Sole source for Medical/Legal advice</li>
                                <li>• Political Propaganda at scale</li>
                                <li>• Automated Misinformation</li>
                            </ul>
                        </div>
                    </div>
                </div>
            )
        },
        {
            id: 'transparency',
            title: "5. AI Safety & Transparency",
            icon: <Eye className="w-5 h-5 text-primary" />,
            content: (
                <div className="space-y-3 text-sm text-subtext">
                    <p><strong>Hallucination Warning:</strong> AI models can generate confident but incorrect info. Verify critical facts.</p>
                    <p><strong>Bias Mitigation:</strong> We use Google’s safety filters and continuously tune to minimize societal biases.</p>
                    <p><strong>Watermarking:</strong> AI-generated images/videos on Free/Starter plans embed a <strong>SynthID</strong> watermark.</p>
                </div>
            )
        }
    ];

    return (
        <div className="h-full flex flex-col bg-background overflow-hidden">
            <header className="px-6 py-5 border-b border-border bg-secondary/30 backdrop-blur-md sticky top-0 z-10">
                <div className="flex items-center gap-3">
                    <div className="p-2 bg-primary/10 rounded-lg">
                        <FileCheck className="w-6 h-6 text-primary" />
                    </div>
                    <div>
                        <h1 className="text-2xl font-bold text-maintext">Trust, Safety & Compliance</h1>
                        <p className="text-xs text-subtext">Version 1.0 | Effective: {new Date().toLocaleDateString()}</p>
                    </div>
                </div>
            </header>

            <div className="flex-1 overflow-y-auto p-6 space-y-8 pb-20">
                <div className="max-w-4xl mx-auto space-y-6">
                    <motion.div
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="bg-primary/5 border border-primary/10 rounded-2xl p-6"
                    >
                        <h2 className="text-xl font-bold text-primary mb-2 flex items-center gap-2">
                            <Zap className="w-5 h-5" /> A-Series™ Performance & Safety
                        </h2>
                        <p className="text-subtext leading-relaxed text-sm">
                            A-Series™ is India's first AI App Marketplace, powered by UWO™. We combine top-tier AI capabilities with enterprise-grade security to ensure that your innovation remains secure, private, and compliant with national laws.
                        </p>
                    </motion.div>

                    <div className="space-y-4">
                        {sections.map((section, idx) => (
                            <motion.section
                                key={section.id}
                                initial={{ opacity: 0, x: -20 }}
                                animate={{ opacity: 1, x: 0 }}
                                transition={{ delay: idx * 0.1 }}
                                className="bg-secondary border border-border rounded-2xl p-6 shadow-sm"
                            >
                                <div className="flex items-center gap-3 mb-4">
                                    <div className="p-2 bg-surface rounded-lg">
                                        {section.icon}
                                    </div>
                                    <h3 className="text-lg font-bold text-maintext">{section.title}</h3>
                                </div>
                                <div>{section.content}</div>
                            </motion.section>
                        ))}
                    </div>

                    <div className="bg-surface border border-border rounded-xl p-5 text-center">
                        <p className="text-subtext text-xs italic">
                            For any emergencies or incident reporting, please use the Support portal in your dashboard.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default TrustSafetyCompliance;
